#!/usr/bin/env python3
"""
Verify TESSCut conditional detrending outputs.

This script validates that a parquet file generated by tesscut_conditional_detrending.ipynb
is internally consistent and that generated detrended FITS files are structurally valid.

Example:
    python verify_detrended_light_curves.py \
        /data/projects/TESS-research/detrending/TESSAugmented_QC_tesscut_conditional_detrended.parquet \
        --max-workers 16 \
        --report-csv /data/projects/TESS-research/detrending/detrend_verification_report.csv

Optional path resolution:
    If FITS paths in the parquet are relative, pass --fits-root /path/to/base/folder.
"""

from __future__ import annotations

import argparse
import math
import os
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
from astropy.io import fits


DEFAULT_REQUIRED_COLUMNS = [
    "provenance",
    "rawLightCurvePath",
    "trendDetectionEligible",
    "trendDetectedForDetrend",
    "trendDetectionStatus",
    "trendFractionSegmentsWithDrift",
    "trendValidSegmentCount",
    "trendSegmentDriftCount",
    "detrendEligible",
    "detrended",
    "detrendStatus",
    "detrendReason",
    "detrendMethod",
    "detrendLightCurvePath",
    "detrendResolvedRawFitsPath",
    "detrendSegmentCount",
    "detrendCorrectedSegmentCount",
    "detrendError",
]


def is_missing(value: Any) -> bool:
    """True for None/NaN/empty-string-like values."""
    if value is None:
        return True
    if isinstance(value, float) and math.isnan(value):
        return True
    if isinstance(value, str) and value.strip() == "":
        return True
    return False


def as_bool(value: Any) -> bool:
    """Convert common parquet/object bool-ish values to bool safely."""
    if is_missing(value):
        return False
    if isinstance(value, (bool, np.bool_)):
        return bool(value)
    if isinstance(value, (int, np.integer)):
        return value != 0
    if isinstance(value, str):
        return value.strip().lower() in {"true", "1", "yes", "y"}
    return bool(value)


def as_int(value: Any, default: int = 0) -> int:
    if is_missing(value):
        return default
    try:
        return int(value)
    except Exception:
        return default


def resolve_path(value: Any, *, parquet_dir: Path, fits_root: Optional[Path]) -> Optional[Path]:
    """Resolve absolute or relative paths from parquet columns."""
    if is_missing(value):
        return None
    p = Path(str(value))
    if p.is_absolute():
        return p

    candidates: List[Path] = []
    if fits_root is not None:
        candidates.append(fits_root / p)
        candidates.append(fits_root / p.name)
    candidates.append(parquet_dir / p)
    candidates.append(Path.cwd() / p)

    for candidate in candidates:
        if candidate.exists():
            return candidate

    # Return the most likely path even if it does not exist, so diagnostics are useful.
    return candidates[0] if candidates else p


def load_time_flux(path: Path) -> Tuple[np.ndarray, np.ndarray, List[str], fits.Header]:
    """Load TIME/FLUX from HDU[1] and return column names and header."""
    with fits.open(path, memmap=False) as hdul:
        if len(hdul) <= 1 or hdul[1].data is None:
            raise ValueError("missing HDU[1] table")
        data = hdul[1].data
        names = list(data.names or [])
        if "TIME" not in names or "FLUX" not in names:
            raise ValueError(f"HDU[1] missing TIME/FLUX columns; columns={names}")
        time = np.asarray(data["TIME"], dtype=float)
        flux = np.asarray(data["FLUX"], dtype=float)
        header = hdul[1].header.copy()
    return time, flux, names, header


def load_original_flux(path: Path) -> Optional[np.ndarray]:
    with fits.open(path, memmap=False) as hdul:
        if len(hdul) <= 1 or hdul[1].data is None:
            return None
        data = hdul[1].data
        names = list(data.names or [])
        if "ORIGINAL_FLUX" not in names:
            return None
        return np.asarray(data["ORIGINAL_FLUX"], dtype=float)


def compare_arrays_close(a: np.ndarray, b: np.ndarray, *, rtol: float, atol: float) -> bool:
    """Compare arrays including NaNs in same locations."""
    if a.shape != b.shape:
        return False
    a_nan = ~np.isfinite(a)
    b_nan = ~np.isfinite(b)
    if not np.array_equal(a_nan, b_nan):
        return False
    finite = np.isfinite(a) & np.isfinite(b)
    if not finite.any():
        return True
    return bool(np.allclose(a[finite], b[finite], rtol=rtol, atol=atol))


def verify_row(
    idx: int,
    row_dict: Dict[str, Any],
    *,
    parquet_dir: Path,
    fits_root: Optional[Path],
    rtol: float,
    atol: float,
) -> Dict[str, Any]:
    """Verify one parquet row and optionally inspect raw/detrended FITS."""
    problems: List[str] = []
    warnings: List[str] = []

    provenance = row_dict.get("provenance")
    is_tesscut = provenance == "TESSCut"
    trend_eligible = as_bool(row_dict.get("trendDetectionEligible"))
    detrend_eligible = as_bool(row_dict.get("detrendEligible"))
    trend_detected = as_bool(row_dict.get("trendDetectedForDetrend"))
    detrended = as_bool(row_dict.get("detrended"))
    detrend_status = row_dict.get("detrendStatus")

    raw_path = resolve_path(
        row_dict.get("detrendResolvedRawFitsPath") or row_dict.get("rawLightCurvePath"),
        parquet_dir=parquet_dir,
        fits_root=fits_root,
    )
    detrended_path = resolve_path(
        row_dict.get("detrendLightCurvePath"),
        parquet_dir=parquet_dir,
        fits_root=fits_root,
    )

    # Metadata consistency checks.
    if not is_tesscut:
        if trend_eligible:
            problems.append("non-TESSCut row has trendDetectionEligible=True")
        if detrend_eligible:
            problems.append("non-TESSCut row has detrendEligible=True")
        if trend_detected:
            problems.append("non-TESSCut row has trendDetectedForDetrend=True")
        if detrended:
            problems.append("non-TESSCut row has detrended=True")
        if detrended_path is not None:
            warnings.append("non-TESSCut row has non-empty detrendLightCurvePath")
        return {
            "row_index": idx,
            "provenance": provenance,
            "detrended": detrended,
            "trendDetectedForDetrend": trend_detected,
            "status": "ok" if not problems else "error",
            "problem_count": len(problems),
            "warning_count": len(warnings),
            "problems": "; ".join(problems),
            "warnings": "; ".join(warnings),
            "raw_path": str(raw_path) if raw_path else "",
            "detrended_path": str(detrended_path) if detrended_path else "",
        }

    # TESSCut rows should be eligible, unless your workflow was intentionally changed.
    if not trend_eligible:
        problems.append("TESSCut row has trendDetectionEligible=False")
    if not detrend_eligible:
        problems.append("TESSCut row has detrendEligible=False")

    if raw_path is None:
        problems.append("TESSCut row has no resolved raw FITS path")
    elif not raw_path.exists():
        problems.append(f"resolved raw FITS does not exist: {raw_path}")

    valid_segments = as_int(row_dict.get("trendValidSegmentCount"))
    drift_segments = as_int(row_dict.get("trendSegmentDriftCount"))
    detrend_segments = as_int(row_dict.get("detrendSegmentCount"))
    corrected_segments = as_int(row_dict.get("detrendCorrectedSegmentCount"))
    fraction_segments = row_dict.get("trendFractionSegmentsWithDrift")

    if trend_detected:
        if valid_segments <= 0:
            problems.append("trendDetected=True but trendValidSegmentCount<=0")
        if drift_segments <= 0:
            problems.append("trendDetected=True but trendSegmentDriftCount<=0")
        try:
            if not is_missing(fraction_segments) and float(fraction_segments) < 0.5:
                problems.append("trendDetected=True but trendFractionSegmentsWithDrift<0.5")
        except Exception:
            problems.append("trendFractionSegmentsWithDrift is not numeric")

    if detrended:
        if not trend_detected:
            problems.append("detrended=True but trendDetectedForDetrend=False")
        if detrend_status != "detrended":
            problems.append(f"detrended=True but detrendStatus={detrend_status!r}")
        if detrended_path is None:
            problems.append("detrended=True but detrendLightCurvePath is empty")
        elif not detrended_path.exists():
            problems.append(f"detrended FITS does not exist: {detrended_path}")
        else:
            if detrended_path.name.endswith("_raw.fits"):
                problems.append("detrended path still ends with _raw.fits")
            if not detrended_path.name.endswith("_detrended.fits"):
                warnings.append("detrended path does not end with _detrended.fits")
        if detrend_segments <= 0:
            problems.append("detrended=True but detrendSegmentCount<=0")
        if corrected_segments <= 0:
            problems.append("detrended=True but detrendCorrectedSegmentCount<=0")
        if corrected_segments > detrend_segments > 0:
            problems.append("detrendCorrectedSegmentCount > detrendSegmentCount")
    else:
        if detrend_status == "detrended":
            problems.append("detrended=False but detrendStatus='detrended'")
        if trend_detected and detrend_status not in {"failed", "insufficient_data", "no_valid_segments"}:
            # In the notebook, detected TESSCut rows should normally produce detrended=True.
            problems.append(
                "trendDetected=True but detrended=False without expected failure/insufficient/no_valid_segments status"
            )

    # FITS-level checks for actually detrended rows.
    if detrended and raw_path is not None and raw_path.exists() and detrended_path is not None and detrended_path.exists():
        try:
            raw_time, raw_flux, raw_names, raw_header = load_time_flux(raw_path)
            det_time, det_flux, det_names, det_header = load_time_flux(detrended_path)
            original_flux = load_original_flux(detrended_path)

            if len(raw_time) != len(det_time):
                problems.append(f"row count mismatch: raw={len(raw_time)} detrended={len(det_time)}")
            if not compare_arrays_close(raw_time, det_time, rtol=rtol, atol=atol):
                problems.append("TIME column mismatch between raw and detrended FITS")
            if "ORIGINAL_FLUX" not in det_names:
                problems.append("detrended FITS missing ORIGINAL_FLUX column")
            elif original_flux is not None and not compare_arrays_close(raw_flux, original_flux, rtol=rtol, atol=atol):
                problems.append("ORIGINAL_FLUX does not match raw FITS FLUX")

            if bool(det_header.get("DETRND", False)) is not True:
                problems.append("detrended FITS header DETRND is not True")
            if "DTRMETH" not in det_header:
                problems.append("detrended FITS header missing DTRMETH")
            if "DTRTHR" not in det_header:
                problems.append("detrended FITS header missing DTRTHR")
            if "DTRFRAC" not in det_header:
                problems.append("detrended FITS header missing DTRFRAC")
            if "GAPDAYS" not in det_header:
                problems.append("detrended FITS header missing GAPDAYS")

            finite_raw = np.isfinite(raw_flux)
            finite_det = np.isfinite(det_flux)
            if not np.array_equal(finite_raw, finite_det):
                warnings.append("finite FLUX mask differs between raw and detrended FITS")

            finite_both = finite_raw & finite_det
            if finite_both.any():
                changed = np.abs(det_flux[finite_both] - raw_flux[finite_both]) > (atol + rtol * np.abs(raw_flux[finite_both]))
                changed_count = int(np.sum(changed))
                if changed_count == 0:
                    problems.append("detrended FITS FLUX appears identical to raw FLUX")
            else:
                problems.append("no finite overlapping FLUX values between raw and detrended FITS")

        except Exception as exc:
            problems.append(f"FITS validation failed: {type(exc).__name__}: {exc}")

    return {
        "row_index": idx,
        "provenance": provenance,
        "detrended": detrended,
        "trendDetectedForDetrend": trend_detected,
        "status": "ok" if not problems else "error",
        "problem_count": len(problems),
        "warning_count": len(warnings),
        "problems": "; ".join(problems),
        "warnings": "; ".join(warnings),
        "raw_path": str(raw_path) if raw_path else "",
        "detrended_path": str(detrended_path) if detrended_path else "",
    }


def summarize(df: pd.DataFrame, report: pd.DataFrame) -> None:
    print("\n=== Parquet summary ===")
    print(f"Rows: {len(df):,}")
    if "provenance" in df.columns:
        print("\nRows by provenance:")
        print(df["provenance"].value_counts(dropna=False).to_string())
    for col in ["trendDetectedForDetrend", "detrended", "detrendStatus"]:
        if col in df.columns:
            print(f"\n{col}:")
            print(df[col].value_counts(dropna=False).to_string())

    print("\n=== Verification summary ===")
    print(report["status"].value_counts(dropna=False).to_string())
    print(f"Rows with errors: {(report['status'] == 'error').sum():,}")
    print(f"Total problems: {int(report['problem_count'].sum()):,}")
    print(f"Total warnings: {int(report['warning_count'].sum()):,}")

    if (report["status"] == "error").any():
        print("\nTop error patterns:")
        exploded = report.loc[report["status"] == "error", "problems"].str.split("; ").explode()
        print(exploded.value_counts().head(20).to_string())


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Verify TESSCut detrended FITS outputs against metadata parquet.")
    parser.add_argument("parquet_file", type=Path, help="Input parquet file to verify")
    parser.add_argument("--fits-root", type=Path, default=None, help="Optional base folder for relative FITS paths")
    parser.add_argument("--max-workers", type=int, default=os.cpu_count() or 4, help="Parallel worker count")
    parser.add_argument("--report-csv", type=Path, default=None, help="Optional CSV report output path")
    parser.add_argument("--only-detrended", action="store_true", help="Only run detailed checks on rows with detrended=True")
    parser.add_argument("--fail-on-errors", action="store_true", help="Exit with code 1 if any verification errors are found")
    parser.add_argument("--rtol", type=float, default=1e-5, help="Relative tolerance for FITS array comparisons")
    parser.add_argument("--atol", type=float, default=1e-6, help="Absolute tolerance for FITS array comparisons")
    args = parser.parse_args(argv)

    if not args.parquet_file.exists():
        print(f"ERROR: parquet file does not exist: {args.parquet_file}", file=sys.stderr)
        return 2

    print(f"Reading parquet: {args.parquet_file}")
    df = pd.read_parquet(args.parquet_file)
    parquet_dir = args.parquet_file.resolve().parent

    missing_columns = [c for c in DEFAULT_REQUIRED_COLUMNS if c not in df.columns]
    if missing_columns:
        print("ERROR: parquet is missing required columns:", file=sys.stderr)
        for c in missing_columns:
            print(f"  - {c}", file=sys.stderr)
        return 2

    work_df = df
    if args.only_detrended:
        work_df = df[df["detrended"].apply(as_bool)].copy()
        print(f"Filtering to detrended=True rows: {len(work_df):,}")

    records = [(int(idx) if isinstance(idx, (int, np.integer)) else idx, row.to_dict()) for idx, row in work_df.iterrows()]
    print(f"Verifying rows: {len(records):,} with max_workers={args.max_workers}")

    results: List[Dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=max(1, args.max_workers)) as executor:
        futures = [
            executor.submit(
                verify_row,
                idx,
                row_dict,
                parquet_dir=parquet_dir,
                fits_root=args.fits_root,
                rtol=args.rtol,
                atol=args.atol,
            )
            for idx, row_dict in records
        ]
        for i, future in enumerate(as_completed(futures), start=1):
            results.append(future.result())
            if i % 500 == 0:
                print(f"  verified {i:,}/{len(futures):,}")

    report = pd.DataFrame(results).sort_values("row_index") if results else pd.DataFrame()
    summarize(df, report)

    if args.report_csv is not None:
        args.report_csv.parent.mkdir(parents=True, exist_ok=True)
        report.to_csv(args.report_csv, index=False)
        print(f"\nSaved verification report: {args.report_csv}")

    if args.fail_on_errors and not report.empty and (report["status"] == "error").any():
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
